var dataProduct = [
	{
		title: "Bàn phím Keychron K2 HE màu đen",
		short_url: "keychron-k2-he",
		sort_description: "",
		description: `<p>Giới thiệu <b>Keychron K2 HE</b>, một cuộc cách mạng trong thế giới bàn phím cơ không dây. Với bố cục 75% nhỏ gọn nhưng đầy đủ chức năng, K2 HE là sự cân bằng hoàn hảo giữa không gian làm việc tối giản và hiệu suất tối đa. Đây không chỉ là một bản nâng cấp, mà là một định nghĩa lại hoàn toàn về trải nghiệm gõ phím nhờ vào công nghệ Switch Từ tính (Magnetic Switch) Hall Effect đột phá.<p><b>Công nghệ Switch Từ tính Hall Effect:</b> Trái tim của K2 HE là các switch từ tính tiên tiến. Khác với switch cơ học truyền thống, switch từ tính sử dụng hiệu ứng Hall để phát hiện vị trí của phím bấm với độ chính xác tuyệt đối. Điều này mở ra những khả năng tùy chỉnh chưa từng có:<ul class="list-disc pl-5"><li><strong>Tùy chỉnh điểm kích hoạt:</strong> Dễ dàng điều chỉnh khoảng cách nhận phím trong khoảng từ 0.1mm đến 4.0mm. Thiết lập một hành trình siêu ngắn (0.1mm) để có phản ứng tức thì trong game, hoặc một hành trình sâu hơn cho việc gõ văn bản chính xác và ít lỗi hơn.<li><strong>Rapid Trigger:</strong> Tính năng thay đổi cuộc chơi cho game thủ. Phím sẽ được reset ngay khi bạn bắt đầu nhấc ngón tay lên, cho phép lặp lại các thao tác nhấn phím với tốc độ cực nhanh, mang lại lợi thế vượt trội trong các game đối kháng và FPS.<li><strong>Độ bền vượt trội:</strong> Với ít tiếp xúc vật lý hơn, switch từ tính có tuổi thọ lên đến 100 triệu lần nhấn, gấp đôi so với các switch cơ học thông thường.</ul><p><b>Kết nối linh hoạt & Tương thích toàn diện:</b> Keychron K2 HE hỗ trợ kết nối qua Bluetooth 5.1 và 2.4GHz không dây, cũng như chế độ có dây USB-C. Dễ dàng chuyển đổi giữa tối đa 3 thiết bị qua Bluetooth. Bàn phím hoàn toàn tương thích với cả macOS và Windows, với bộ keycap đi kèm cho cả hai hệ điều hành.<p><b>Thiết kế cao cấp:</b> Bàn phím được trang bị keycap PBT double-shot cao cấp, chống mài mòn và chống bám dầu, đảm bảo vẻ ngoài luôn như mới. Bên trong, nhiều lớp foam tiêu âm được tích hợp để loại bỏ các âm thanh không mong muốn, mang lại trải nghiệm gõ êm ái và dễ chịu.`,
		image_path: "./img/Product-1.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 13,
		originalPrice: 129.99,
		discountedPrice: 129.99,
		category: "bàn phím",
		quantity: 15,
	},
	{
		title: "Bàn phím số tùy chỉnh không dây Keychron Q0 Max QMK",
		sort_description: "",
		short_url: "keychron-q0-max-qmk",
		description: `<p><b>Keychron Q0 Max</b>là mảnh ghép còn thiếu để hoàn thiện không gian làm việc chuyên nghiệp của bạn. Đây không chỉ là một bàn phím số thông thường, mà là một công cụ năng suất mạnh mẽ, được chế tác tinh xảo và trang bị những công nghệ hàng đầu. Với thân máy hoàn toàn bằng kim loại, kết nối không dây và khả năng tùy chỉnh vô hạn qua QMK/VIA, Q0 Max được sinh ra để tối ưu hóa mọi quy trình làm việc.</p><p><b>Thiết kế kim loại nguyên khối và Gasket Mount:</b>Q0 Max kế thừa chất lượng xây dựng đỉnh cao của dòng Q-series với thân máy được gia công từ nhôm CNC 6063, mang lại sự chắc chắn, đầm tay và vẻ ngoài cao cấp. Cấu trúc Gasket Mount, với các miếng đệm silicon giữa plate và vỏ, giúp hấp thụ rung động, tạo ra trải nghiệm gõ linh hoạt và âm thanh "thocky" đầy thỏa mãn mà các tín đồ phím cơ yêu thích.</p><p><b>Sức mạnh của QMK/VIA:</b>Giải phóng toàn bộ tiềm năng của bạn với phần mềm QMK/VIA. Bạn có thể dễ dàng lập trình lại bất kỳ phím nào trên Q0 Max. Gán các chuỗi lệnh phức tạp, các phím tắt chuyên dụng cho phần mềm (Excel, Photoshop, AutoCAD, v.v.), hoặc tạo các lớp phím chức năng khác nhau. Núm xoay (knob) cũng có thể được tùy chỉnh để điều khiển âm lượng, độ sáng, cuộn trang, zoom, hoặc bất kỳ chức năng nào bạn có thể nghĩ ra, giúp tăng tốc công việc một cách đáng kinh ngạc.</p><p><b>Kết nối không dây 2.4GHz & Bluetooth:</b>Tận hưởng sự tự do và một bàn làm việc gọn gàng với kết nối không dây kép. Sử dụng kết nối 2.4GHz với polling rate 1000Hz để có độ trễ cực thấp, hoặc kết nối qua Bluetooth 5.1 với tối đa 3 thiết bị và chuyển đổi liền mạch giữa chúng. Tất nhiên, chế độ có dây USB-C vẫn luôn sẵn sàng.</p>`,
		image_path: "./img/Product-2.webp",
		banner_image_path: "",
		star_rate: 4.5,
		rate_count: 17,
		originalPrice: 64.99,
		discountedPrice: 64.99,
		category: "khác",
		quantity: 10,
	},
	{
		title: "Bàn phím cơ Keychron Q6 Max",
		sort_description: "",
		short_url: "keychron-q6-max",
		description: `<p><b>Keychron Q6 Max</b>là đỉnh cao của dòng bàn phím cơ full-size, mang đến một trải nghiệm gõ không thể so sánh và chất lượng xây dựng ở một đẳng cấp hoàn toàn khác. Được thiết kế cho những người đam mê thực thụ và các chuyên gia yêu cầu những gì tốt nhất, Q6 Max kết hợp thân máy hoàn toàn bằng kim loại, kết nối không dây 2.4GHz và Bluetooth, cùng khả năng tùy biến vô hạn với QMK/VIA.</p><p><b>Chất lượng xây dựng đỉnh cao:</b>Toàn bộ thân máy của Q6 Max được chế tác từ một khối nhôm 6063 duy nhất, trải qua 24 công đoạn sản xuất bao gồm CNC, đánh bóng, và anodizing. Điều này không chỉ tạo ra một chiếc bàn phím cực kỳ bền bỉ và chắc chắn mà còn mang lại trọng lượng đầm tay, giúp ổn định trên bàn làm việc và nâng cao trải nghiệm gõ.</p><p><b>Trải nghiệm gõ tuyệt hảo với Gasket Mount:</b>Thiết kế Double Gasket Mount cải tiến mang lại cảm giác gõ linh hoạt và âm thanh trong trẻo, thỏa mãn. Bằng cách đặt các miếng đệm silicon trên cả vỏ trên và dưới, cấu trúc này cho phép plate và PCB có độ uốn lượn nhẹ, giảm thiểu các rung động tần số cao và tạo ra một sound profile độc đáo, êm ái hơn.</p><p><b>Kết nối không dây mạnh mẽ cho năng suất tối đa:</b>Với kết nối không dây 2.4GHz có polling rate 1000 Hz, Q6 Max mang lại hiệu suất phản hồi tức thì, lý tưởng cho cả công việc và chơi game. Ngoài ra, bạn có thể kết nối với tối đa 3 thiết bị qua Bluetooth 5.1, dễ dàng chuyển đổi giữa máy tính, laptop và máy tính bảng chỉ bằng một nút bấm.</p>`,
		image_path: "./img/Product-3.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 11,
		originalPrice: 219.99,
		discountedPrice: 209.99,
		category: "bàn phím",
		quantity: 5,
	},
	{
		title: "Bàn phím cơ Keychron K4 Max",
		sort_description: "",
		short_url: "keychron-k4-max",
		description: `<p><b>Keychron K4 Max</b>là giải pháp tối ưu cho những ai cần đầy đủ các phím của một bàn phím full-size nhưng lại muốn tiết kiệm không gian bàn làm việc. Với bố cục 96% thông minh, K4 Max giữ lại gần như toàn bộ các phím chức năng và cụm phím số trong một thiết kế nhỏ gọn hơn đáng kể. Được nâng cấp với kết nối không dây 2.4GHz và Bluetooth 5.1, cùng với khả năng tùy chỉnh QMK/VIA, K4 Max là một cỗ máy năng suất thực thụ.</p><p><b>Bố cục 96% - Hiệu quả tối đa:</b>Thiết kế 96% loại bỏ các khoảng trống không cần thiết, giúp K4 Max nhỏ gọn hơn 20% so với bàn phím full-size truyền thống mà vẫn giữ lại cụm phím số tiện lợi. Đây là sự lựa chọn hoàn hảo cho việc nhập liệu, lập trình, và các công việc văn phòng đòi hỏi hiệu suất cao.</p><p><b>Nâng cao trải nghiệm gõ:</b>K4 Max được trang bị nhiều lớp foam tiêu âm, bao gồm IXPE switch pad và foam đáy, giúp giảm thiểu đáng kể các âm thanh rỗng và tạo ra một trải nghiệm gõ êm ái, chắc chắn hơn. Cấu trúc được gia cố bằng khung nhôm mang lại sự ổn định và bền bỉ.</p><p><b>Tùy chỉnh không giới hạn với QMK/VIA:</b>Giống như các dòng cao cấp, K4 Max giờ đây cũng hỗ trợ QMK/VIA. Điều này cho phép bạn lập trình lại mọi phím, tạo các macro phức tạp, và cá nhân hóa bàn phím để phù hợp hoàn hảo với quy trình làm việc của bạn. Thay đổi keymap, gán các phím tắt, tất cả đều có thể thực hiện một cách trực quan và dễ dàng.</p>`,
		image_path: "./img/Product-4.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 17,
		originalPrice: 134.99,
		discountedPrice: 134.99,
		category: "bàn phím",
		quantity: 8,
	},
	{
		title: "Bàn phím cơ low-profile Keychron K5 Max",
		sort_description: "",
		short_url: "keychron-k5-max",
		description: `<p><b>Keychron K5 Max</b>định nghĩa lại khái niệm về bàn phím cơ mỏng nhẹ. Với thiết kế low-profile siêu mỏng, K5 Max mang lại cảm giác gõ thoải mái và nhanh nhạy mà không chiếm nhiều diện tích, lý tưởng cho những người thường xuyên di chuyển hoặc yêu thích một không gian làm việc tối giản. Dù mỏng nhẹ, K5 Max vẫn được trang bị đầy đủ sức mạnh với kết nối không dây và khả năng tùy chỉnh QMK/VIA.</p><p><b>Thiết kế siêu mỏng, hiệu suất tối đa:</b>K5 Max sử dụng switch Gateron low-profile, giúp giảm đáng kể chiều cao tổng thể của bàn phím mà vẫn giữ được cảm giác gõ cơ học đặc trưng. Bố cục full-size 100% đảm bảo bạn không bỏ lỡ bất kỳ phím chức năng nào, giúp tối ưu hóa năng suất làm việc.</p><p><b>Linh hoạt và di động:</b>Khung nhôm gia cố mang lại sự chắc chắn cần thiết trong một thân hình mỏng nhẹ. Dễ dàng mang theo K5 Max bên mình và kết nối với laptop, máy tính bảng hay điện thoại qua Bluetooth 5.1.</p><p><b>Sức mạnh tùy chỉnh trong tầm tay:</b>Lần đầu tiên, một bàn phím low-profile của Keychron được trang bị khả năng tùy chỉnh QMK/VIA. Giờ đây bạn có thể lập trình lại mọi phím, tạo macro, và cá nhân hóa bàn phím theo cách bạn muốn, biến K5 Max thành một công cụ độc nhất dành riêng cho bạn.</p>`,
		image_path: "./img/Product-5.webp",
		banner_image_path: "",
		star_rate: 3.5,
		rate_count: 21,
		originalPrice: 94.99,
		discountedPrice: 89.99,
		category: "bàn phím",
		quantity: 0,
	},
	{
		title: "Đệm kê tay silicon Keychron",
		sort_description: "",
		short_url: "keychron-silicon",
		description: `<p><b>Nâng cao sự thoải mái, tối ưu hóa công thái học.</b>Đệm kê tay silicon của Keychron là phụ kiện không thể thiếu cho bất kỳ ai dành nhiều giờ làm việc hoặc chơi game trên bàn phím. Được thiết kế để cung cấp sự hỗ trợ tối ưu cho cổ tay, sản phẩm này giúp duy trì tư thế gõ tự nhiên, giảm thiểu căng thẳng và ngăn ngừa các vấn đề về cổ tay trong dài hạn.</p><p><b>Chất liệu Silicon cao cấp:</b>Được làm từ silicon chất lượng cao, đệm kê tay mang lại cảm giác mềm mại, êm ái nhưng vẫn đủ chắc chắn để nâng đỡ cổ tay của bạn. Bề mặt mịn màng, dễ dàng vệ sinh và chống bám bụi bẩn.</p><p><b>Thiết kế chống trượt:</b>Mặt dưới của đệm kê tay được thiết kế với bề mặt chống trượt, đảm bảo nó luôn cố định trên bàn làm việc của bạn, ngay cả trong những phiên chơi game căng thẳng nhất. Bạn có thể tập trung hoàn toàn vào công việc mà không bị phân tâm.</p><p><b>Tương thích hoàn hảo:</b>Với nhiều kích thước khác nhau, đệm kê tay silicon Keychron được thiết kế để phù hợp hoàn hảo với các dòng bàn phím của hãng, từ layout 65% nhỏ gọn đến full-size, tạo nên một tổng thể thẩm mỹ và liền mạch cho không gian làm việc của bạn.</p>`,
		image_path: "./img/Product-6.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 10,
		originalPrice: 9.99,
		discountedPrice: 9.99,
		category: "khác",
		quantity: 30,
	},
	{
		title: "Chuột không dây Keychron M3",
		sort_description: "",
		short_url: "keychron-m3",
		description: `<p><b>Keychron M3</b>được thiết kế để trở thành con chuột toàn năng, đáp ứng mọi nhu cầu từ công việc văn phòng đòi hỏi sự chính xác đến những trận game đỉnh cao. Với trọng lượng chỉ 79g và trang bị cảm biến hàng đầu, M3 mang lại sự thoải mái, tốc độ và độ chính xác vượt trội để bạn luôn làm chủ tình hình.</p><p><b>Cảm biến PixArt 3395 hàng đầu:</b>Trung tâm của M3 là cảm biến quang học PixArt 3395, một trong những cảm biến tốt nhất trên thị trường. Với DPI lên đến 26,000, polling rate 1000 Hz và IPS 650, M3 đảm bảo khả năng tracking 1:1 hoàn hảo, không gia tốc, không trễ, mang lại độ chính xác tuyệt đối trong mọi cú di chuột.</p><p><b>Kết nối không dây kép, ổn định tuyệt đối:</b>Tận hưởng sự tự do với hai chế độ kết nối không dây. Chế độ 2.4GHz mang lại kết nối ổn định với độ trễ cực thấp, lý tưởng cho gaming. Chế độ Bluetooth 5.1 cho phép bạn dễ dàng kết nối với nhiều thiết bị khác nhau.</p><p><b>Thiết kế công thái học siêu nhẹ:</b>Với trọng lượng chỉ 79 gram, M3 giúp giảm thiểu mỏi tay khi sử dụng trong thời gian dài. Thiết kế công thái học đối xứng phù hợp với nhiều kiểu cầm chuột khác nhau, đảm bảo sự thoải mái và khả năng kiểm soát tối ưu.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.5,
		rate_count: 33,
		originalPrice: 39.99,
		discountedPrice: 35.99,
		category: "chuột",
		quantity: 0,
	},
	{
		title: "Bàn phím số tùy chỉnh không dây Keychron Q0 Max QMK",
		short_url: "keychron-q0-max-qmk-2",
		sort_description: "",
		description: `<p><b>Keychron Q0 Max</b>là người bạn đồng hành không thể thiếu cho chiếc bàn phím tenkeyless hoặc 65% của bạn. Được thiết kế như một bàn phím số (numpad) độc lập, Q0 Max không chỉ giúp bạn xử lý các con số một cách nhanh chóng mà còn là một công cụ macro mạnh mẽ nhờ vào khả năng tùy chỉnh vô hạn với QMK/VIA.</p><p><b>Chất lượng xây dựng đỉnh cao:</b>Giống như các sản phẩm dòng Q Max khác, Q0 Max được chế tác từ một khối nhôm CNC 6063, mang lại cảm giác cực kỳ chắc chắn và cao cấp. Cấu trúc Gasket Mount đảm bảo trải nghiệm gõ êm ái, linh hoạt và giảm thiểu tiếng ồn không mong muốn.</p><p><b>Biến thành bảng điều khiển Macro:</b>Sức mạnh thực sự của Q0 Max nằm ở khả năng tùy chỉnh. Với phần mềm VIA, bạn có thể dễ dàng gán các chuỗi lệnh phức tạp, các phím tắt cho ứng dụng, hoặc các chức năng đặc biệt cho từng phím. Biến nó thành một bảng điều khiển cho công việc thiết kế, chỉnh sửa video, hoặc thậm chí là chơi game.</p><p><b>Kết nối không dây, đồng bộ hoàn hảo:</b>Kết nối Q0 Max với máy tính của bạn qua Bluetooth 5.1 hoặc 2.4GHz để có một bàn làm việc hoàn toàn không dây. Đặt nó ở bất cứ đâu bạn cảm thấy thuận tiện nhất, bên trái hoặc bên phải bàn phím chính của bạn.</p>`,
		image_path: "./img/Product-8.webp",
		banner_image_path: "",
		star_rate: 4,
		rate_count: 21,
		originalPrice: 119.99,
		discountedPrice: 119.99,
		category: "khác",
		quantity: 12,
	},
	{
		title: "Cáp xoắn Keychron Coiled Aviator",
		sort_description: "",
		short_url: "keychron-coiled-cable",
		description: `<p><b>Nâng tầm thẩm mỹ cho góc làm việc của bạn.</b>Cáp xoắn Keychron Coiled Aviator là một phụ kiện cao cấp được thiết kế để mang lại vẻ ngoài chuyên nghiệp, gọn gàng và đầy phong cách cho bàn phím cơ của bạn. Đoạn cáp xoắn không chỉ đẹp mắt mà còn giúp quản lý dây cáp hiệu quả, giữ cho bàn làm việc luôn ngăn nắp.</p><p><b>Đầu nối Aviator có thể tháo rời:</b>Điểm nhấn của sợi cáp là đầu nối Aviator 5-pin có thể tháo rời. Đầu nối kim loại chắc chắn này không chỉ tạo điểm nhấn thẩm mỹ mà còn mang lại sự tiện lợi, cho phép bạn nhanh chóng thay đổi hoặc tháo rời bàn phím mà không cần phải rút dây khỏi máy tính.</p><p><b>Bền bỉ và linh hoạt:</b>Cáp được bọc bằng chất liệu Thermoplastic Elastomer (TPE) linh hoạt và bền bỉ, bên trong là lớp vỏ bện chắc chắn, đảm bảo tuổi thọ cao và khả năng chống rối. Sợi cáp được thiết kế để cung cấp nguồn điện ổn định và truyền dữ liệu đáng tin cậy.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 17,
		originalPrice: 13.99,
		discountedPrice: 13.99,
		category: "khác",
		quantity: 40,
	},
	{
		title: "Keycap Artisan Kim loại Búp bê Daruma",
		short_url: "keycap-daruma",
		sort_description: "",
		description: `<p><b>Thể hiện cá tính, mang lại may mắn.</b>Keycap artisan búp bê Daruma của Keychron không chỉ là một món đồ trang trí, mà còn là một tác phẩm nghệ thuật mang đậm ý nghĩa văn hóa. Được chế tác từ hợp kim kẽm cao cấp, mỗi keycap là một điểm nhấn độc đáo, thể hiện sự tinh tế và cá tính của người sở hữu.</p><p><b>Biểu tượng của sự kiên trì và may mắn:</b>Trong văn hóa Nhật Bản, búp bê Daruma là biểu tượng cho sự kiên trì, quyết tâm và may mắn. Đặt keycap này lên phím Escape hoặc bất kỳ phím chức năng nào bạn yêu thích như một lời nhắc nhở về mục tiêu của mình và một lá bùa may mắn cho công việc và cuộc sống.</p><p><b>Chế tác tinh xảo:</b>Mỗi keycap được đúc và sơn thủ công một cách tỉ mỉ, đảm bảo độ chi tiết cao và chất lượng hoàn thiện vượt trội. Chất liệu kim loại mang lại cảm giác gõ đầm tay và âm thanh độc đáo.</p><p><b>Tương thích rộng rãi:</b>Keycap Daruma tương thích với hầu hết các switch cơ học có stem hình chữ thập (cross-stem) như Gateron, Cherry, Kailh, v.v. Đây là món quà hoàn hảo cho bản thân hoặc cho bất kỳ người bạn nào đam mê bàn phím cơ.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 8,
		originalPrice: 13.99,
		discountedPrice: 10.99,
		category: "keycap",
		quantity: 0,
	},
	{
		title: "Chuột không dây Keychron M5 8K",
		short_url: "keychron-m5-8k",
		sort_description: "Switch từ tính | 2.4 GHz & Bluetooth",
		description: `<p><b>Keychron M5 8K</b>là vũ khí tối thượng dành cho game thủ chuyên nghiệp. Được trang bị những công nghệ tiên tiến nhất, M5 8K mang lại tốc độ, độ chính xác và khả năng phản hồi chưa từng có. Với polling rate 8000Hz, switch từ tính siêu bền và kết nối không dây kép, đây là con chuột được sinh ra để chiến thắng.</p><p><b>Polling Rate 8000Hz - Tốc độ ánh sáng:</b>Trải nghiệm sự mượt mà tuyệt đối với polling rate 8K ở chế độ có dây và 4K ở chế độ không dây 2.4GHz. Tốc độ truyền dữ liệu siêu nhanh giúp giảm độ trễ xuống mức gần như bằng không, mang lại lợi thế quyết định trong mọi pha xử lý.</p><p><b>Switch từ tính quang học:</b>Các nút bấm chính sử dụng switch từ tính quang học, mang lại tốc độ phản hồi tức thì và độ bền lên đến 100 triệu lần nhấn. Loại bỏ hoàn toàn hiện tượng double-click không mong muốn và đảm bảo mọi cú click của bạn đều được ghi nhận một cách chính xác.</p><p><b>Kết nối 2.4GHz & Bluetooth:</b>Tự do lựa chọn giữa kết nối 2.4GHz độ trễ thấp cho gaming hoặc Bluetooth 5.1 tiện lợi cho công việc hàng ngày. Dễ dàng chuyển đổi giữa các thiết bị để tối ưu hóa quy trình làm việc của bạn.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "./img/banner.webp",
		star_rate: 4.5,
		rate_count: 45,
		originalPrice: 89.99,
		discountedPrice: 89.99,
		category: "chuột",
		quantity: 18,
	},
	{
		title: "Bàn phím cơ Black Myth: Wukong Edition",
		short_url: "keychron-wukong-editon",
		sort_description:
			"2.4GHz & Bluetooth | Thân kim loại nguyên khối | Keycap PBT",
		description: `<p><b>Một huyền thoại tái sinh.</b>Hợp tác cùng tựa game được mong chờ nhất, Keychron tự hào giới thiệu phiên bản đặc biệt<b>Black Myth: Wukong</b>. Đây không chỉ là một chiếc bàn phím, mà là một tác phẩm nghệ thuật, kết hợp giữa công nghệ đỉnh cao và cảm hứng từ một trong những câu chuyện vĩ đại nhất.</p><p><b>Thân kim loại nguyên khối:</b>Cảm nhận sức mạnh của Ngộ Không qua thân máy được chế tác từ nhôm nguyên khối, mang lại sự chắc chắn và vẻ ngoài uy nghiêm. Các họa tiết được khắc laser tinh xảo, lấy cảm hứng từ các yếu tố trong game, biến chiếc bàn phím thành một vật phẩm sưu tầm độc đáo.</p><p><b>Keycap PBT Dye-Sub Huyền Thoại:</b>Bộ keycap được làm từ nhựa PBT siêu bền với công nghệ in Dye-Sublimation, đảm bảo các ký tự và họa tiết không bao giờ phai mờ. Font chữ và các biểu tượng được thiết kế riêng, mang đậm không khí thần thoại của Black Myth: Wukong.</p><p><b>Hiệu suất đỉnh cao:</b>Bên trong vẻ ngoài huyền thoại là hiệu suất hiện đại. Bàn phím hỗ trợ kết nối không dây 2.4GHz và Bluetooth, cùng với cấu trúc Gasket Mount cho trải nghiệm gõ êm ái, thỏa mãn. Sẵn sàng cùng bạn chinh phục mọi thử thách, từ công việc đến những trận chiến cam go nhất.</p>`,
		image_path: "./img/Product-3.webp",
		banner_image_path: "./img/wukong-banner.webp",
		star_rate: 5,
		rate_count: 58,
		originalPrice: 249.99,
		discountedPrice: 249.99,
		category: "bàn phím",
		quantity: 3,
	},
	{
		title: "Keychron B33",
		short_url: "keychron-b33",
		sort_description: "Cơ chế cắt kéo | 2,4 GHz & Bluetooth | Phím Slient",
		description:
			"<p><b>Sự tĩnh lặng tinh tế.</b> Keychron B33 là hiện thân của sự tinh tế và hiệu quả, được thiết kế đặc biệt cho những ai tìm kiếm một không gian làm việc yên tĩnh. Điểm nhấn cốt lõi của sản phẩm này nằm ở <b>cơ chế phím cắt kéo (scissor-switch)</b> tiên tiến, mang lại phản hồi nhanh nhạy nhưng vẫn đảm bảo sự êm ái gần như không tiếng động, lý tưởng cho môi trường văn phòng mở hoặc làm việc đêm khuya.</p><p><b>Kết nối đa năng.</b> Không chỉ dừng lại ở trải nghiệm gõ tĩnh lặng, Keychron B33 còn mang đến sự linh hoạt vượt trội với <b>kết nối kép mạnh mẽ</b>. Bạn có thể dễ dàng chuyển đổi giữa kết nối không dây <b>2.4GHz</b> độ trễ thấp và kết nối <b>Bluetooth</b> tiện lợi để ghép nối với nhiều thiết bị. Đây là sự lựa chọn hoàn hảo cho những ai ưu tiên sự yên tĩnh và một không gian làm việc gọn gàng, hiệu quả.</p>",
		image_path: "./img/Product-7.webp",
		banner_image_path: "./img/Banner-3.webp",
		star_rate: 5,
		rate_count: 58,
		originalPrice: 249.99,
		discountedPrice: 229.99,
		category: "bàn phím",
		quantity: 9,
	},
	{
		short_url: "keychron-b36",
		title: "Keychron B36",
		sort_description:
			"2.4GHz & Bluetooth | Thân kim loại nguyên khối | Keycap PBT",
		description:
			"<p><b>Tuyệt tác kim loại.</b> Keychron B36 là một tuyệt tác của kỹ thuật, hướng đến những người dùng yêu cầu sự hoàn mỹ cả về thẩm mỹ lẫn độ bền. Đặc điểm đắt giá nhất chính là <b>bộ khung kim loại nguyên khối (unibody)</b> được chế tác tinh xảo, mang lại vẻ ngoài sang trọng, cảm giác cầm nắm chắc chắn và một nền tảng gõ phím ổn định tuyệt đối.</p><p><b>Trải nghiệm cao cấp.</b> Nâng tầm trải nghiệm là bộ <b>keycap PBT chất lượng hàng đầu</b>, nổi tiếng với độ bền vượt trội, chống mài mòn và chống phai màu hiệu quả. Kết hợp cùng kết nối kép linh hoạt <b>2.4GHz & Bluetooth</b>, Keychron B36 mang đến một trải nghiệm gõ phím đỉnh cao, bền bỉ với thời gian cho những ai đánh giá cao vật liệu và chất lượng gia công.</p>",
		image_path: "./img/Product-6.webp",
		banner_image_path: "./img/Banner-4.jpg",
		star_rate: 5,
		rate_count: 58,
		originalPrice: 249.99,
		discountedPrice: 249.99,
		category: "bàn phím",
		quantity: 11,
	},
	{
		title: "Keychron C2 Pro 8K",
		short_url: "keychron-c2-pro-8k",
		sort_description: "Switch từ tính | 2.4 GHz & Bluetooth",
		description:
			"<p><b>Vũ khí tối thượng cho game thủ.</b> Keychron C2 Pro 8K được sinh ra để thống trị về tốc độ và độ nhạy, dành cho các game thủ chuyên nghiệp và người dùng đòi hỏi sự chính xác tuyệt đối. Trái tim của nó là <b>công nghệ switch từ tính (magnetic switch)</b> đột phá, cho phép tùy chỉnh điểm nhận phím và đăng ký lệnh với tốc độ cực nhanh, mang lại lợi thế cạnh tranh rõ rệt.</p><p><b>Tốc độ ánh sáng.</b> Đẩy hiệu suất lên một tầm cao mới là <b>tần số lấy mẫu 8000Hz</b> ở chế độ không dây <b>2.4GHz</b>, giúp giảm độ trễ xuống gần như bằng không. Mọi lệnh đều được thực thi tức thì, đảm bảo không có khoảnh khắc nào ảnh hưởng đến kết quả. Dù được tối ưu cho tốc độ đỉnh cao, C2 Pro 8K vẫn giữ lại sự linh hoạt của kết nối <b>Bluetooth</b> cho các tác vụ hàng ngày.</p>",
		image_path: "./img/Product-5.webp",
		banner_image_path: "./img/Banner-5.jpg",
		star_rate: 5,
		rate_count: 58,
		originalPrice: 249.99,
		discountedPrice: 249.99,
		category: "bàn phím",
		quantity: 6,
	},
	{
		title: "Chuột Keychron M1 Max",
		short_url: "keychron-m1-max",
		sort_description: "Cảm biến quang học | 16,000 DPI",
		description:
			"<p><b>Độ chính xác tối đa.</b> Chuột Keychron M1 Max được trang bị cảm biến quang học PixArt PMW3389 hàng đầu, mang lại độ chính xác và khả năng theo dõi vượt trội với DPI lên đến 16,000. Thiết kế công thái học dành cho người thuận tay phải, đảm bảo sự thoải mái trong nhiều giờ sử dụng liên tục.</p>",
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 55,
		originalPrice: 59.99,
		discountedPrice: 49.99,
		category: "chuột",
		quantity: 22,
	},
	{
		title: "Chuột công thái học Keychron M6",
		short_url: "keychron-m6",
		sort_description: "Thiết kế dọc | Bánh xe cuộn kép",
		description:
			"<p><b>Công thái học đỉnh cao.</b> Keychron M6 định nghĩa lại sự thoải mái với thiết kế công thái học dọc, giúp giảm căng thẳng cho cổ tay và cánh tay. Được trang bị bánh xe cuộn kép (một dọc, một ngang), M6 là công cụ hoàn hảo cho các nhà thiết kế, lập trình viên và những người làm việc với bảng tính nhiều.</p>",
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 68,
		originalPrice: 79.99,
		discountedPrice: 79.99,
		category: "chuột",
		quantity: 14,
	},
	{
		title: "Bộ Switch Keychron Gateron G Pro 3.0 (35 Pcs)",
		short_url: "keychron-gateron-g-pro-3",
		sort_description: "Linear / Tactile / Clicky | Lò xo 2 tầng",
		description:
			"<p><b>Nâng cấp trải nghiệm gõ của bạn.</b> Bộ switch Gateron G Pro 3.0 là lựa chọn tuyệt vời để tùy chỉnh bàn phím cơ của bạn. Với nhiều tùy chọn (Red, Brown, Blue), bạn có thể tìm thấy cảm giác gõ hoàn hảo cho mình. Lò xo hai tầng mang lại phản hồi nhất quán và âm thanh thỏa mãn.</p>",
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 40,
		originalPrice: 15.99,
		discountedPrice: 15.99,
		category: "khác",
		quantity: 50,
	},
	{
		title: "Bộ Keycap PBT OSA Profile - 'Developer'",
		short_url: "keycap-set-developer",
		sort_description: "PBT Double-Shot | OSA Profile",
		description:
			"<p><b>Dành cho lập trình viên.</b> Lấy cảm hứng từ các theme code editor, bộ keycap 'Developer' mang đến một vẻ ngoài sạch sẽ và chuyên nghiệp cho bàn phím của bạn. Được làm từ nhựa PBT double-shot siêu bền, các ký tự sẽ không bao giờ phai mờ. Profile OSA mang lại cảm giác gõ thoải mái và độc đáo.</p>",
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 32,
		originalPrice: 59.0,
		discountedPrice: 55.0,
		category: "keycap",
		quantity: 20,
	},
	{
		title: "Bàn phím cơ Keychron V1 Max",
		short_url: "keychron-v1-max",
		sort_description: "75% Layout | QMK/VIA | 2.4GHz & Bluetooth",
		description: `<p><b>Keychron V1 Max</b> là sự lựa chọn hoàn hảo cho những ai muốn bước vào thế giới bàn phím cơ tùy chỉnh mà không tốn quá nhiều chi phí. Với layout 75% nhỏ gọn, kết nối không dây 2.4GHz và Bluetooth, cùng khả năng tùy chỉnh mạnh mẽ qua QMK/VIA, V1 Max mang lại trải nghiệm cao cấp trong một mức giá dễ tiếp cận.</p><p><b>Tùy chỉnh không giới hạn:</b> V1 Max hỗ trợ đầy đủ QMK/VIA, cho phép bạn lập trình lại mọi phím, tạo macro và cá nhân hóa hoàn toàn bàn phím theo ý muốn. Khả năng hot-swap cho phép bạn dễ dàng thay đổi switch mà không cần hàn, mở ra một thế giới tùy biến vô tận.</p><p><b>Trải nghiệm gõ tuyệt vời:</b> Cấu trúc Gasket Mount mang lại cảm giác gõ linh hoạt và âm thanh êm ái. Plate PC và nhiều lớp foam tiêu âm được trang bị sẵn giúp loại bỏ các âm thanh không mong muốn, mang lại trải nghiệm gõ thỏa mãn ngay từ khi mở hộp.</p>`,
		image_path: "./img/Product-1.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 25,
		originalPrice: 99.99,
		discountedPrice: 99.99,
		category: "bàn phím",
		quantity: 15,
	},
	{
		title: "Bàn phím cơ Keychron K8 Pro HE (Hall Effect)",
		short_url: "keychron-k8-pro-he",
		sort_description: "TKL Layout | Switch từ tính | Rapid Trigger",
		description: `<p><b>Keychron K8 Pro HE</b> nâng cấp layout Tenkeyless (TKL) cổ điển lên một tầm cao mới với công nghệ Switch Từ tính Hall Effect. Đây là sự kết hợp hoàn hảo giữa thiết kế quen thuộc và hiệu suất đột phá, lý tưởng cho cả game thủ và người dùng chuyên nghiệp.</p><p><b>Công nghệ Switch Từ tính:</b> Tận hưởng khả năng tùy chỉnh điểm kích hoạt từ 0.1mm đến 4.0mm. Kích hoạt tính năng Rapid Trigger để có phản ứng tức thì trong game, cho phép lặp lại thao tác nhấn phím với tốc độ không tưởng. Độ bền 100 triệu lần nhấn đảm bảo hiệu suất bền bỉ.</p><p><b>Chất lượng xây dựng Pro:</b> Kế thừa những gì tốt nhất của dòng K Pro, K8 Pro HE được trang bị keycap PBT double-shot, foam tiêu âm và stabilizer được lube sẵn, mang lại trải nghiệm gõ mượt mà và chắc chắn.</p>`,
		image_path: "./img/Product-4.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 18,
		originalPrice: 149.99,
		discountedPrice: 145.99,
		category: "bàn phím",
		quantity: 10,
	},
	{
		title: "Bàn phím cơ Keychron Q1 HE (Hall Effect)",
		short_url: "keychron-q1-he",
		sort_description: "75% Layout | Thân kim loại | Switch từ tính",
		description: `<p><b>Keychron Q1 HE</b> là phiên bản được mong chờ nhất của dòng Q1, nay được trang bị công nghệ Switch Từ tính Hall Effect tiên tiến. Giữ nguyên thiết kế thân kim loại CNC cao cấp và cấu trúc Double Gasket Mount, Q1 HE mang đến một trải nghiệm gõ không thể so sánh, kết hợp giữa cảm giác cao cấp và hiệu suất gaming đỉnh cao.</p><p><b>Hiệu suất từ tính:</b> Tùy chỉnh hành trình phím, bật Rapid Trigger và trải nghiệm độ chính xác tuyệt đối. Q1 HE là vũ khí tối thượng cho các game thủ cạnh tranh, đồng thời vẫn mang lại sự linh hoạt cho công việc sáng tạo.</p><p><b>Thiết kế đỉnh cao:</b> Thân máy bằng nhôm 6063, keycap PBT double-shot profile KSA và hệ thống LED RGB South-facing rực rỡ. Mọi chi tiết trên Q1 HE đều được chế tác một cách tỉ mỉ để mang lại sự hoàn hảo.</p>`,
		image_path: "./img/Product-3.webp",
		banner_image_path: "./img/banner.webp",
		star_rate: 5,
		rate_count: 35,
		originalPrice: 229.99,
		discountedPrice: 229.99,
		category: "bàn phím",
		quantity: 7,
	},
	{
		title: "Bàn phím cơ low-profile Keychron K3 Max",
		short_url: "keychron-k3-max",
		sort_description: "75% Low-profile | QMK/VIA | 2.4GHz & Bluetooth",
		description: `<p><b>Keychron K3 Max</b> là phiên bản nâng cấp toàn diện của bàn phím low-profile 75% bán chạy nhất. Nay được trang bị kết nối không dây 2.4GHz, hỗ trợ QMK/VIA và cải thiện đáng kể về âm thanh, K3 Max là lựa chọn hoàn hảo cho những ai yêu thích sự mỏng nhẹ, di động mà không muốn hy sinh hiệu suất.</p><p><b>Mỏng hơn, mạnh hơn:</b> Thiết kế siêu mỏng với switch Gateron low-profile 2.0 cho cảm giác gõ ổn định hơn. Khả năng tùy chỉnh QMK/VIA lần đầu tiên xuất hiện trên K3, cho phép bạn cá nhân hóa hoàn toàn layout và macro.</p><p><b>Cải thiện âm thanh:</b> K3 Max được bổ sung thêm foam tiêu âm bên trong, giúp giảm thiểu tiếng ồn và mang lại âm thanh gõ chắc chắn, dễ chịu hơn so với các phiên bản trước.</p>`,
		image_path: "./img/Product-5.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 22,
		originalPrice: 119.99,
		discountedPrice: 114.99,
		category: "bàn phím",
		quantity: 20,
	},
	{
		title: "Bàn phím cơ gaming Lemokey L3",
		short_url: "lemokey-l3",
		sort_description: "TKL Layout | Thân kim loại | Polling Rate 1000Hz",
		description: `<p><b>Lemokey L3</b> là bàn phím TKL được thiết kế dành riêng cho game thủ từ thương hiệu con của Keychron. Với thân máy hoàn toàn bằng kim loại, kết nối không dây 2.4GHz có polling rate 1000Hz và khả năng tùy chỉnh QMK/VIA, L3 mang lại hiệu suất, độ bền và sự linh hoạt mà các game thủ yêu cầu.</p><p><b>Thiết kế cho game thủ:</b> Layout TKL (80%) là tiêu chuẩn vàng cho gaming, cung cấp đủ không gian cho chuột. Núm xoay có thể tùy chỉnh giúp bạn điều khiển âm lượng, zoom hoặc gán bất kỳ chức năng nào một cách nhanh chóng.</p><p><b>Bền bỉ và ổn định:</b> Thân máy bằng nhôm CNC nguyên khối đảm bảo sự ổn định tuyệt đối trong các trận chiến căng thẳng. Keycap PBT double-shot chống mài mòn và bám dầu, giữ cho bàn phím luôn như mới.</p>`,
		image_path: "./img/Product-3.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 31,
		originalPrice: 199.99,
		discountedPrice: 199.99,
		category: "bàn phím",
		quantity: 12,
	},
	{
		title: "Bàn phím cơ Keychron V5 Max",
		short_url: "keychron-v5-max",
		sort_description: "1800-Compact Layout | QMK/VIA | Không dây",
		description: `<p><b>Keychron V5 Max</b> mang đến layout 1800-compact (96%) hiệu quả, giữ lại gần như đầy đủ các phím của một bàn phím full-size trong một kích thước nhỏ gọn hơn. Đây là phiên bản không dây của dòng V, được trang bị kết nối 2.4GHz và Bluetooth, lý tưởng cho những ai cần cụm phím số nhưng vẫn muốn tiết kiệm không gian.</p><p><b>Hiệu suất tối đa:</b> Hỗ trợ QMK/VIA, hot-swappable, và cấu trúc Gasket Mount, V5 Max mang lại trải nghiệm gõ và khả năng tùy chỉnh tuyệt vời. Đây là cỗ máy năng suất thực thụ cho công việc nhập liệu và lập trình.</p><p><b>Thiết kế thông minh:</b> Layout 1800-compact sắp xếp các phím một cách hợp lý, giúp bạn dễ dàng truy cập tất cả các chức năng cần thiết mà không cần di chuyển tay quá nhiều.</p>`,
		image_path: "./img/Product-4.webp",
		banner_image_path: "",
		star_rate: 4.6,
		rate_count: 15,
		originalPrice: 109.99,
		discountedPrice: 109.99,
		category: "bàn phím",
		quantity: 18,
	},
	{
		title: "Bàn phím cơ công thái học Keychron Q14 Pro",
		short_url: "keychron-q14-pro",
		sort_description: "Alice Layout | Numpad trái | Thân kim loại",
		description: `<p><b>Keychron Q14 Pro</b> là một thiết kế đột phá, kết hợp layout Alice công thái học với một cụm phím số đầy đủ và một cột phím macro bên trái. Được chế tác từ nhôm CNC nguyên khối, Q14 Pro được sinh ra để tối ưu hóa sự thoải mái và năng suất cho các chuyên gia.</p><p><b>Thiết kế công thái học:</b> Layout Alice chia bàn phím thành hai nửa góc cạnh, giúp cổ tay và cánh tay ở vị trí tự nhiên hơn, giảm thiểu căng thẳng khi gõ trong thời gian dài. Cụm phím số bên trái lý tưởng cho việc nhập liệu, cho phép tay phải của bạn luôn đặt trên chuột.</p><p><b>Sức mạnh Pro:</b> Kết nối không dây, QMK/VIA, cấu trúc Double Gasket Mount và chất lượng xây dựng đỉnh cao của dòng Q Pro. Q14 Pro là một công cụ mạnh mẽ và độc đáo dành cho những người dùng chuyên nghiệp.</p>`,
		image_path: "./img/Product-2.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 9,
		originalPrice: 255.99,
		discountedPrice: 245.99,
		category: "bàn phím",
		quantity: 5,
	},
	{
		title: "Bàn phím cơ low-profile Keychron K15 Pro",
		short_url: "keychron-k15-pro",
		sort_description: "75% Alice Low-profile | QMK/VIA | RGB",
		description: `<p><b>Keychron K15 Pro</b> mang thiết kế công thái học Alice đến với thế giới bàn phím low-profile. Đây là sự kết hợp hoàn hảo giữa sự thoải mái, tính di động và hiệu suất. Với layout 75% Alice, K15 Pro giúp giảm mỏi tay trong khi vẫn giữ được thiết kế siêu mỏng và nhẹ.</p><p><b>Công thái học di động:</b> Tận hưởng những lợi ích của layout Alice trong một thân hình mỏng nhẹ, dễ dàng mang theo. K15 Pro là người bạn đồng hành lý tưởng cho những ai thường xuyên di chuyển.</p><p><b>Sức mạnh QMK/VIA:</b> Lần đầu tiên, một bàn phím low-profile Alice được trang bị khả năng tùy chỉnh QMK/VIA, cho phép bạn cá nhân hóa hoàn toàn trải nghiệm gõ của mình.</p>`,
		image_path: "./img/Product-5.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 14,
		originalPrice: 139.99,
		discountedPrice: 139.99,
		category: "bàn phím",
		quantity: 11,
	},
	{
		title: "Bàn phím cơ Keychron Q8 Max",
		short_url: "keychron-q8-max",
		sort_description: "65% Alice Layout | Không dây | Thân kim loại",
		description: `<p><b>Keychron Q8 Max</b> là phiên bản không dây được nâng cấp của bàn phím công thái học Alice 65% nổi tiếng. Giữ nguyên thân máy bằng nhôm CNC cao cấp và cấu trúc Gasket Mount, Q8 Max nay được bổ sung kết nối 2.4GHz và Bluetooth, mang lại một không gian làm việc công thái học và hoàn toàn không dây.</p><p><b>Nhỏ gọn và thoải mái:</b> Layout 65% Alice loại bỏ hàng phím chức năng nhưng vẫn giữ lại các phím mũi tên, tạo ra một thiết kế cực kỳ nhỏ gọn và thoải mái. Lý tưởng cho những ai yêu thích sự tối giản và công thái học.</p><p><b>Trải nghiệm gõ cao cấp:</b> Cấu trúc Double Gasket Mount, keycap PBT và stabilizer được cải tiến mang lại cảm giác gõ và âm thanh tuyệt vời, xứng tầm với dòng Q Max.</p>`,
		image_path: "./img/Product-3.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 20,
		originalPrice: 215.99,
		discountedPrice: 205.99,
		category: "bàn phím",
		quantity: 8,
	},
	{
		title: "Bàn phím cơ Keychron V10",
		short_url: "keychron-v10",
		sort_description: "70% Alice Layout | QMK/VIA | Hot-swap",
		description: `<p><b>Keychron V10</b> mang thiết kế công thái học Alice đến với dòng V series dễ tiếp cận. Với layout 70%, V10 bổ sung thêm một hàng phím chức năng so với layout 65% Alice, mang lại sự tiện lợi hơn cho công việc. Đây là điểm khởi đầu tuyệt vời để trải nghiệm layout công thái học.</p><p><b>Công thái học cho mọi người:</b> V10 cung cấp tất cả các tính năng cốt lõi của dòng V: hỗ trợ QMK/VIA, hot-swappable, stabilizer bắt vít và núm xoay có thể lập trình, tất cả trong một thiết kế Alice 70% độc đáo.</p><p><b>Chất lượng đáng tin cậy:</b> Mặc dù có mức giá phải chăng, V10 vẫn được trang bị plate PC, foam silicon và keycap PBT double-shot để đảm bảo trải nghiệm gõ chất lượng cao.</p>`,
		image_path: "./img/Product-1.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 19,
		originalPrice: 89.99,
		discountedPrice: 89.99,
		category: "bàn phím",
		quantity: 25,
	},
	{
		title: "Bộ Keycap Keychron OSA Profile PBT - '8008'",
		short_url: "keycap-set-8008",
		sort_description: "PBT Double-Shot | OSA Profile | Tương thích rộng",
		description: `<p><b>Lấy cảm hứng từ phối màu cổ điển.</b> Bộ keycap '8008' mang đến một vẻ ngoài hoài cổ nhưng không kém phần hiện đại cho bàn phím của bạn. Với tông màu xám, đen và hồng đặc trưng, bộ keycap này là một điểm nhấn phong cách. Chất liệu PBT double-shot đảm bảo ký tự không bao giờ phai, trong khi profile OSA mang lại trải nghiệm gõ độc đáo và thoải mái.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 42,
		originalPrice: 69.0,
		discountedPrice: 65.0,
		category: "keycap",
		quantity: 30,
	},
	{
		title: "Bộ Keycap Keychron Cherry Profile PBT Dye-Sub - 'Matcha'",
		short_url: "keycap-set-matcha",
		sort_description: "PBT Dye-Sub | Cherry Profile | Font chữ tối giản",
		description: `<p><b>Sự thanh lịch của trà xanh.</b> Bộ keycap 'Matcha' mang đến một không gian làm việc nhẹ nhàng và thư thái. Với các sắc thái xanh lá cây và trắng kem, bộ keycap này tạo ra một vẻ ngoài sạch sẽ và tinh tế. Công nghệ in Dye-Sublimation cho phép các thiết kế phức tạp và bền màu, trong khi Cherry profile quen thuộc mang lại cảm giác gõ thoải mái cho cả chơi game và làm việc.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 38,
		originalPrice: 59.0,
		discountedPrice: 59.0,
		category: "keycap",
		quantity: 25,
	},
	{
		title: "Bộ Keycap Keychron KSA Profile PBT Double-Shot - 'Carbon'",
		short_url: "keycap-set-carbon",
		sort_description: "PBT Double-Shot | KSA Profile | Phối màu tương phản",
		description: `<p><b>Mạnh mẽ và nổi bật.</b> Lấy cảm hứng từ sợi carbon, bộ keycap này kết hợp màu xám đậm, đen và cam để tạo ra một vẻ ngoài công nghệ cao và đầy năng lượng. Profile KSA độc quyền của Keychron có chiều cao tương tự SA nhưng với đỉnh keycap hình cầu, mang lại cảm giác gõ chắc chắn và âm thanh 'thocky' đặc trưng.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 51,
		originalPrice: 65.0,
		discountedPrice: 59.0,
		category: "keycap",
		quantity: 18,
	},
	{
		title: "Bộ Keycap Keychron OSA Profile PBT Dye-Sub - 'Japanese Root'",
		short_url: "keycap-set-japanese-root",
		sort_description: "PBT Dye-Sub | OSA Profile | Ký tự Hiragana",
		description: `<p><b>Vẻ đẹp tối giản của Nhật Bản.</b> Bộ keycap 'Japanese Root' mang đến sự tinh tế với tông màu trắng và đen cổ điển, được bổ sung bởi các ký tự Hiragana màu đỏ. Công nghệ in Dye-Sub đảm bảo các ký tự sắc nét và bền bỉ. Profile OSA mang lại cảm giác gõ thoải mái và thẩm mỹ độc đáo cho bất kỳ bàn phím nào.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 45,
		originalPrice: 69.0,
		discountedPrice: 69.0,
		category: "keycap",
		quantity: 22,
	},
	{
		title: "Bộ Keycap Keychron Cherry Profile PBT Double-Shot - 'WoB'",
		short_url: "keycap-set-wob",
		sort_description: "PBT Double-Shot | Cherry Profile | Trắng trên Đen",
		description: `<p><b>Sự tương phản kinh điển.</b> 'White on Black' (WoB) là một trong những phối màu keycap không bao giờ lỗi thời. Sự đơn giản và tương phản cao giúp nó phù hợp với mọi loại vỏ bàn phím. Chất liệu PBT double-shot siêu bền và Cherry profile quen thuộc làm cho bộ keycap này trở thành một lựa chọn an toàn và đáng tin cậy cho mọi người dùng.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 60,
		originalPrice: 55.0,
		discountedPrice: 49.0,
		category: "keycap",
		quantity: 40,
	},
	{
		title: "Bộ Keycap Keychron OSA Profile PBT Dye-Sub - 'Chalk'",
		short_url: "keycap-set-chalk",
		sort_description: "PBT Dye-Sub | OSA Profile | Màu sắc Pastel",
		description: `<p><b>Nhẹ nhàng như phấn viết.</b> Bộ keycap 'Chalk' sử dụng các màu pastel nhẹ nhàng trên nền trắng kem, tạo ra một vẻ ngoài vui tươi và sạch sẽ. Các ký tự được in bằng công nghệ Dye-Sub, đảm bảo độ bền và sắc nét. Đây là lựa chọn hoàn hảo để làm bừng sáng không gian làm việc của bạn.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 28,
		originalPrice: 65.0,
		discountedPrice: 65.0,
		category: "keycap",
		quantity: 0,
	},
	{
		title: "Bộ Keycap Keychron KSA Profile PBT Double-Shot - 'Laser'",
		short_url: "keycap-set-laser",
		sort_description: "PBT Double-Shot | KSA Profile | Cảm hứng Cyberpunk",
		description: `<p><b>Thẩm mỹ tương lai.</b> Lấy cảm hứng từ thập niên 80 và thế giới cyberpunk, bộ keycap 'Laser' kết hợp màu xanh đậm, tím và hồng neon để tạo ra một vẻ ngoài cực kỳ nổi bật và ấn tượng. Profile KSA cao và hình cầu mang lại âm thanh gõ sâu và cảm giác độc đáo, hoàn thiện chủ đề retro-futuristic.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 55,
		originalPrice: 70.0,
		discountedPrice: 65.0,
		category: "keycap",
		quantity: 15,
	},
	{
		title: "Bộ Keycap Keychron Cherry Profile PBT Dye-Sub - 'Botanical'",
		short_url: "keycap-set-botanical",
		sort_description: "PBT Dye-Sub | Cherry Profile | Chủ đề thiên nhiên",
		description: `<p><b>Mang thiên nhiên vào không gian làm việc.</b> Bộ keycap 'Botanical' lấy cảm hứng từ màu xanh tươi mát của lá cây. Với các sắc thái xanh lá cây khác nhau trên nền trắng và xám, bộ keycap này mang lại cảm giác yên bình và gần gũi với thiên nhiên. Chất liệu PBT Dye-Sub và Cherry profile đảm bảo chất lượng và sự thoải mái.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 48,
		originalPrice: 69.0,
		discountedPrice: 69.0,
		category: "keycap",
		quantity: 28,
	},
	{
		title: "Bộ Keycap Keychron OSA Profile PBT Double-Shot - 'Olivia'",
		short_url: "keycap-set-olivia",
		sort_description: "PBT Double-Shot | OSA Profile | Thanh lịch & Tinh tế",
		description: `<p><b>Sự kết hợp hoàn hảo.</b> Phối màu 'Olivia' với tông màu kem, đen và hồng rose-gold đã trở thành một biểu tượng trong cộng đồng. Nó mang lại một vẻ ngoài thanh lịch, tinh tế và cực kỳ linh hoạt. Chất liệu PBT double-shot và profile OSA đảm bảo cả về thẩm mỹ lẫn chất lượng gõ phím.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 72,
		originalPrice: 75.0,
		discountedPrice: 70.0,
		category: "keycap",
		quantity: 10,
	},
	{
		title: "Bộ Keycap Keychron Cherry Profile PBT Dye-Sub - 'Minimalist BoW'",
		short_url: "keycap-set-bow",
		sort_description: "PBT Dye-Sub | Cherry Profile | Đen trên Trắng",
		description: `<p><b>Sự tinh khiết của tối giản.</b> 'Black on White' (BoW) là hiện thân của sự đơn giản. Với các ký tự màu đen sắc nét trên nền trắng tinh khôi, bộ keycap này mang lại một vẻ ngoài cực kỳ sạch sẽ và chuyên nghiệp. Công nghệ in Dye-Sub và profile Cherry quen thuộc là sự đảm bảo cho một trải nghiệm gõ phím tuyệt vời và bền bỉ.</p>`,
		image_path: "./img/Product-10.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 65,
		originalPrice: 55.0,
		discountedPrice: 49.0,
		category: "keycap",
		quantity: 35,
	},
	{
		title: "Chuột không dây Keychron M2",
		short_url: "keychron-m2",
		sort_description: "Cảm biến 26K | 2.4GHz & Bluetooth | Siêu nhẹ 68g",
		description: `<p><b>Keychron M2</b> là phiên bản nhỏ gọn hơn của M3, được thiết kế cho những người dùng có bàn tay nhỏ hơn hoặc ưa thích kiểu cầm claw grip. Dù nhỏ gọn, M2 vẫn được trang bị cảm biến PixArt 3395 hàng đầu, mang lại độ chính xác tuyệt đối. Với trọng lượng chỉ 68g và kết nối không dây kép, M2 là một lựa chọn linh hoạt cho cả công việc và giải trí.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 39,
		originalPrice: 45.99,
		discountedPrice: 39.99,
		category: "chuột",
		quantity: 25,
	},
	{
		title: "Chuột gaming siêu nhẹ Keychron M4",
		short_url: "keychron-m4",
		sort_description: "Trọng lượng 55g | Cảm biến 26K | Thiết kế Honeycomb",
		description: `<p><b>Keychron M4</b> là câu trả lời cho các game thủ tìm kiếm trọng lượng nhẹ nhất có thể. Với thiết kế vỏ honeycomb độc đáo, M4 đạt được trọng lượng đáng kinh ngạc chỉ 55 gram, giúp giảm thiểu mỏi tay và cho phép các cú vẩy chuột nhanh như chớp. Bên trong là cảm biến PixArt 3395 mạnh mẽ và switch Huano siêu bền.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 52,
		originalPrice: 59.99,
		discountedPrice: 59.99,
		category: "chuột",
		quantity: 15,
	},
	{
		title: "Chuột gaming có dây Keychron M1 Pro",
		short_url: "keychron-m1-pro",
		sort_description: "Cảm biến 19K | Polling Rate 4000Hz | Dây Paracord",
		description: `<p><b>Keychron M1 Pro</b> là phiên bản nâng cấp của chuột M1, tập trung vào hiệu suất có dây tối đa. Được trang bị cảm biến PixArt 3389 với DPI 19,000 và polling rate lên đến 4000Hz, M1 Pro mang lại khả năng tracking mượt mà và phản hồi tức thì. Dây cáp paracord siêu mềm giúp giảm thiểu lực cản, cho cảm giác gần như không dây.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 41,
		originalPrice: 49.99,
		discountedPrice: 45.99,
		category: "chuột",
		quantity: 30,
	},
	{
		title: "Chuột công thái học dọc Keychron M7",
		short_url: "keychron-m7",
		sort_description: "Thiết kế dọc | 8 nút lập trình | 2.4GHz & Bluetooth",
		description: `<p><b>Keychron M7</b> được thiết kế để mang lại sự thoải mái tối đa trong thời gian dài sử dụng. Thiết kế công thái học dọc giúp giữ cổ tay ở vị trí 'bắt tay' tự nhiên, giảm căng thẳng cơ bắp. Với 8 nút có thể lập trình và kết nối không dây kép, M7 là công cụ hoàn hảo cho các nhà sáng tạo nội dung và chuyên gia văn phòng.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.6,
		rate_count: 33,
		originalPrice: 69.99,
		discountedPrice: 69.99,
		category: "chuột",
		quantity: 18,
	},
	{
		title: "Chuột gaming Lemokey L1",
		short_url: "lemokey-l1",
		sort_description: "Thân kim loại | Cảm biến 26K | Tùy chỉnh QMK/VIA",
		description: `<p><b>Lemokey L1</b> là chuột gaming cao cấp từ thương hiệu con của Keychron. Điểm độc đáo của L1 là bộ khung hợp kim magie siêu nhẹ nhưng cực kỳ chắc chắn. Được trang bị cảm biến PixArt 3395, kết nối không dây 2.4GHz và đặc biệt là khả năng tùy chỉnh các nút bấm thông qua phần mềm VIA, L1 mang đến sự cá nhân hóa chưa từng có.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 29,
		originalPrice: 99.99,
		discountedPrice: 95.99,
		category: "chuột",
		quantity: 10,
	},
	{
		title: "Chuột không dây Keychron M3 Mini 4K",
		short_url: "keychron-m3-mini-4k",
		sort_description: "Polling Rate 4K | Cảm biến 26K | Siêu nhẹ 59g",
		description: `<p><b>Keychron M3 Mini 4K</b> là phiên bản thu nhỏ và nâng cấp của M3. Với trọng lượng chỉ 59g và kích thước nhỏ gọn, nó hoàn hảo cho kiểu cầm fingertip. Điểm nhấn lớn nhất là khả năng hỗ trợ polling rate 4000Hz (yêu cầu dongle 4K riêng), mang lại độ mượt mà và phản hồi vượt trội cho các game thủ chuyên nghiệp.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 48,
		originalPrice: 69.99,
		discountedPrice: 69.99,
		category: "chuột",
		quantity: 22,
	},
	{
		title: "Chuột đối xứng Keychron M8",
		short_url: "keychron-m8",
		sort_description: "Thiết kế đối xứng | 2.4GHz & Bluetooth | Cảm biến 12K",
		description: `<p><b>Keychron M8</b> là lựa chọn hoàn hảo cho những ai cần một con chuột đơn giản, đáng tin cậy và có thể sử dụng bằng cả hai tay. Thiết kế đối xứng hoàn toàn, phù hợp cho cả người dùng thuận tay trái và tay phải. Được trang bị cảm biến PixArt 3327, M8 đáp ứng tốt mọi nhu cầu công việc văn phòng và giải trí hàng ngày.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.5,
		rate_count: 35,
		originalPrice: 29.99,
		discountedPrice: 25.99,
		category: "chuột",
		quantity: 0,
	},
	{
		title: "Chuột MMO Keychron M9",
		short_url: "keychron-m9",
		sort_description: "12 nút hông | Cảm biến 19K | Công thái học",
		description: `<p><b>Keychron M9</b> là vũ khí dành cho các game thủ MMO và MOBA. Với cụm 12 nút bấm cơ học ở bên hông, bạn có thể gán toàn bộ kỹ năng và vật phẩm trong tầm tay. Thiết kế công thái học cho người thuận tay phải và cảm biến PixArt 3389 đảm bảo sự thoải mái và chính xác trong các trận chiến kéo dài.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 44,
		originalPrice: 79.99,
		discountedPrice: 75.99,
		category: "chuột",
		quantity: 13,
	},
	{
		title: "Chuột văn phòng yên tĩnh Keychron M10",
		short_url: "keychron-m10",
		sort_description: "Switch im lặng | 2.4GHz & Bluetooth | Thiết kế mỏng",
		description: `<p><b>Keychron M10</b> được thiết kế cho môi trường làm việc yên tĩnh. Các switch im lặng giảm hơn 90% tiếng ồn khi nhấp chuột, giúp bạn tập trung mà không làm phiền người khác. Thiết kế mỏng, đối xứng và kết nối không dây kép làm cho M10 trở thành người bạn đồng hành lý tưởng cho văn phòng hoặc thư viện.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 55,
		originalPrice: 35.99,
		discountedPrice: 35.99,
		category: "chuột",
		quantity: 40,
	},
	{
		title: "Chuột không dây Keychron M5 Pro",
		short_url: "keychron-m5-pro",
		sort_description: "Switch quang học | Cảm biến 26K | Polling Rate 2K",
		description: `<p><b>Keychron M5 Pro</b> là phiên bản nâng cấp của M5, hướng đến các game thủ yêu cầu cao hơn. Được trang bị switch quang học cho tốc độ phản hồi tức thì và độ bền vượt trội, cùng với khả năng hỗ trợ polling rate 2000Hz ở chế độ không dây 2.4GHz. Cảm biến PixArt 3395 vẫn là trái tim của M5 Pro, đảm bảo hiệu suất tracking đỉnh cao.</p>`,
		image_path: "./img/Product-7.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 40,
		originalPrice: 99.99,
		discountedPrice: 95.99,
		category: "chuột",
		quantity: 9,
	},
	{
		title: "Túi đựng bàn phím Keychron (cho layout 75%/80%)",
		short_url: "keychron-keyboard-case-75",
		sort_description: "Chống sốc | Vải cao cấp | Ngăn phụ kiện",
		description: `<p><b>Bảo vệ tối đa cho bàn phím của bạn.</b> Túi đựng bàn phím Keychron được thiết kế để bảo vệ an toàn cho chiếc bàn phím cơ yêu quý của bạn khi di chuyển. Với lớp lót bên trong dày dặn và vỏ ngoài bằng vải cao cấp, túi giúp chống sốc, chống trầy xước và bụi bẩn hiệu quả. Ngoài ra còn có một ngăn lưới bên trong để bạn đựng cáp và các phụ kiện nhỏ khác.</p>`,
		image_path: "./img/Product-6.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 35,
		originalPrice: 25.0,
		discountedPrice: 25.0,
		category: "khác",
		quantity: 40,
	},
	{
		title: "Bộ dụng cụ Keycap & Switch Puller Keychron",
		short_url: "keychron-puller-kit",
		sort_description: "Thép không gỉ | Tay cầm thoải mái | Đa năng",
		description: `<p><b>Công cụ cần thiết cho người chơi phím cơ.</b> Bộ dụng cụ này bao gồm một keycap puller dạng dây thép và một switch puller chất lượng cao. Keycap puller giúp bạn tháo keycap một cách an toàn mà không làm trầy xước, trong khi switch puller được thiết kế để tháo switch khỏi các bàn phím hot-swap một cách dễ dàng. Đây là bộ đôi không thể thiếu để vệ sinh và tùy chỉnh bàn phím.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 88,
		originalPrice: 9.99,
		discountedPrice: 7.99,
		category: "khác",
		quantity: 150,
	},
	{
		title: "Kê tay bằng gỗ Keychron (cho layout TKL)",
		short_url: "keychron-wooden-palm-rest-tkl",
		sort_description: "Gỗ óc chó nguyên khối | Công thái học | Đế chống trượt",
		description: `<p><b>Nâng cao sự thoải mái và thẩm mỹ.</b> Kê tay bằng gỗ của Keychron được chế tác từ gỗ óc chó nguyên khối, mang lại vẻ ngoài sang trọng và cảm giác tự nhiên. Thiết kế công thái học giúp nâng đỡ cổ tay, giảm mỏi khi gõ phím trong thời gian dài. Mặt dưới có các miếng đệm cao su chống trượt, đảm bảo sự ổn định trên bàn làm việc.</p>`,
		image_path: "./img/Product-6.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 62,
		originalPrice: 35.0,
		discountedPrice: 30.0,
		category: "khác",
		quantity: 20,
	},
	{
		title: "Bộ Keychron Stabilizer V2",
		short_url: "keychron-stabilizer-v2",
		sort_description: "Screw-in | Lube sẵn | Giảm rung lắc",
		description: `<p><b>Nâng cấp trải nghiệm gõ phím.</b> Bộ stabilizer V2 của Keychron được thiết kế để giảm thiểu tối đa sự rung lắc (rattle) của các phím dài như Spacebar, Enter, Shift. Thiết kế screw-in (bắt vít) giúp cố định stabilizer vào PCB một cách chắc chắn. Chúng được lube sẵn từ nhà máy, mang lại cảm giác nhấn mượt mà và ổn định ngay khi lắp đặt.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 45,
		originalPrice: 12.0,
		discountedPrice: 12.0,
		category: "khác",
		quantity: 60,
	},
	{
		title: "Bộ Switch Keychron Phantom (90 Pcs)",
		short_url: "keychron-phantom-switches",
		sort_description: "Lube sẵn | Housing trong mờ | Cảm giác mượt mà",
		description: `<p><b>Trải nghiệm gõ phím cao cấp.</b> Dòng switch Phantom của Keychron được lube sẵn từ nhà máy, mang lại cảm giác nhấn cực kỳ mượt mà và âm thanh dễ chịu. Housing trong mờ giúp tăng cường hiệu ứng của đèn LED RGB. Có sẵn các tùy chọn Red (Linear), Brown (Tactile), và Blue (Clicky) để phù hợp với sở thích của bạn.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 4.9,
		rate_count: 58,
		originalPrice: 35.0,
		discountedPrice: 32.0,
		category: "khác",
		quantity: 30,
	},
	{
		title: "Tấm lót bàn Keychron Desk Mat",
		short_url: "keychron-desk-mat",
		sort_description: "Kích thước lớn | Bề mặt vải mịn | Đế cao su chống trượt",
		description: `<p><b>Hoàn thiện không gian làm việc của bạn.</b> Tấm lót bàn của Keychron có kích thước lớn (900x400mm), đủ chỗ cho cả bàn phím và chuột. Bề mặt vải mịn được tối ưu hóa cho việc di chuột chính xác, trong khi đế cao su dày dặn đảm bảo tấm lót luôn bám chắc vào mặt bàn. Các họa tiết tối giản và logo Keychron tạo nên một vẻ ngoài chuyên nghiệp.</p>`,
		image_path: "./img/Product-6.webp",
		banner_image_path: "",
		star_rate: 4.8,
		rate_count: 75,
		originalPrice: 29.99,
		discountedPrice: 29.99,
		category: "khác",
		quantity: 50,
	},
	{
		title: "Bộ foam tiêu âm cho Keychron Q1/K2",
		short_url: "keychron-acoustic-foam-kit",
		sort_description: "Poron & EVA | Cải thiện âm thanh | Dễ lắp đặt",
		description: `<p><b>Tùy chỉnh âm thanh bàn phím của bạn.</b> Bộ foam này được cắt sẵn để vừa vặn hoàn hảo với các mẫu bàn phím Keychron Q1 hoặc K2. Bao gồm foam Poron cho plate và foam EVA cho đáy vỏ, bộ kit này giúp loại bỏ các âm thanh rỗng và tần số cao không mong muốn, mang lại âm thanh gõ 'thocky' và trầm ấm hơn.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 4.7,
		rate_count: 28,
		originalPrice: 15.0,
		discountedPrice: 15.0,
		category: "khác",
		quantity: 45,
	},
	{
		title: "Núm xoay tùy chỉnh Keychron (Nhôm)",
		short_url: "keychron-custom-knob-aluminum",
		sort_description: "Nhôm CNC | Nhiều màu sắc | Tương thích dòng Q/V",
		description: `<p><b>Tạo điểm nhấn cá nhân.</b> Thay thế núm xoay mặc định trên bàn phím Keychron dòng Q hoặc V của bạn bằng núm xoay nhôm CNC cao cấp. Có sẵn nhiều màu sắc anodized khác nhau như Bạc, Đen, Xanh Navy, và Vàng, giúp bạn dễ dàng phối màu với bộ keycap và vỏ bàn phím để tạo ra một thiết kế độc đáo.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 41,
		originalPrice: 10.0,
		discountedPrice: 8.0,
		category: "khác",
		quantity: 0,
	},
	{
		title: "Dầu lube Krytox GPL 205g0 (5g)",
		short_url: "krytox-205g0-lube",
		sort_description:
			"Lube switch linear | Lube stabilizer | Tiêu chuẩn công nghiệp",
		description: `<p><b>Dành cho người đam mê thực thụ.</b> Krytox 205g0 là loại dầu lube tiêu chuẩn vàng trong cộng đồng phím cơ để lube switch linear và stabilizer. Chỉ một lượng nhỏ có thể làm cho switch của bạn trở nên mượt mà hơn đáng kể và loại bỏ hoàn toàn tiếng rattle của stabilizer. Lọ 5g đủ để lube cho nhiều bàn phím.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 5,
		rate_count: 95,
		originalPrice: 19.99,
		discountedPrice: 19.99,
		category: "khác",
		quantity: 25,
	},
	{
		title: "Bộ O-Ring giảm chấn Keychron (120 Pcs)",
		short_url: "keychron-o-rings",
		sort_description: "Silicon | Giảm tiếng ồn | Rút ngắn hành trình phím",
		description: `<p><b>Tùy chỉnh cảm giác gõ.</b> Bộ O-ring bằng silicon này được đặt vào chân keycap, giúp giảm tiếng ồn khi phím chạm đáy (bottom-out). Nó cũng làm hành trình phím ngắn lại một chút, mang lại cảm giác gõ êm hơn. Đây là một cách đơn giản và hiệu quả để làm cho bàn phím cơ của bạn yên tĩnh hơn cho môi trường văn phòng.</p>`,
		image_path: "./img/Product-9.webp",
		banner_image_path: "",
		star_rate: 4.5,
		rate_count: 66,
		originalPrice: 8.0,
		discountedPrice: 8.0,
		category: "khác",
		quantity: 100,
	},
];
